/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * AltFlex AEGIS v3.0 — Swagger/OpenAPI Specification QA Tests
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Validates the OpenAPI 3.1 specification generated by @fastify/swagger.
 * Ensures all tags, metadata, and route paths are correctly documented.
 *
 * NOTE: Uses inline swagger registration instead of importing swagger.plugin.ts
 * to avoid fastify-plugin CJS resolution issues in Vitest ESM environment.
 *
 * @role Senior SDET — Swagger spec depth validation
 * @task P1-ARCH-011 QA Integration Testing
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import Fastify, { type FastifyInstance } from 'fastify';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import { systemRoutes } from '../src/routes/system.routes.js';
import { hacksRoutes } from '../src/routes/hacks.routes.js';
import { forensicsRoutes } from '../src/routes/forensics.routes.js';
import { skillsRoutes } from '../src/routes/skills.routes.js';

// ═══════════════════════════════════════════════════════════════════════════════
// OpenAPI Spec Shape
// ═══════════════════════════════════════════════════════════════════════════════

interface OpenAPISpec {
  openapi: string;
  info: {
    title: string;
    version: string;
    description: string;
    contact?: { url?: string };
    license?: { name?: string };
  };
  tags: Array<{ name: string; description?: string }>;
  paths: Record<string, unknown>;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Test Server — all routes registered for spec completeness
// ═══════════════════════════════════════════════════════════════════════════════

async function buildSwaggerServer(): Promise<FastifyInstance> {
  const server = Fastify({
    logger: false,
    requestIdHeader: 'x-correlation-id',
  });

  // Register swagger inline (mirrors swagger.plugin.ts)
  await server.register(swagger, {
    openapi: {
      openapi: '3.1.0',
      info: {
        title: 'AltFlex AEGIS API Gateway',
        version: '3.0.0',
        description:
          'Backend-for-Frontend API Gateway for the AltFlex AEGIS v3.0 platform. ' +
          'Provides unified REST API access to the Hacks Dashboard (Engine α), ' +
          'AI Skills Explorer (Engine β), and Forensic Engine (Engine γ).',
        contact: {
          name: 'AltFlex AEGIS Engineering',
          url: 'https://github.com/Artificial-Ledger-Technology/ALT-Flex',
        },
        license: {
          name: 'MIT',
        },
      },
      tags: [
        { name: 'System - Health', description: 'Health checks and liveness probes' },
        { name: 'System - Meta', description: 'System metadata and feature flags' },
        { name: 'System - Auth', description: 'Authentication and token management' },
        { name: 'System - Rate Limit', description: 'Rate limit status and configuration' },
        { name: 'Hacks - List & Filter', description: 'Browse and search hack incidents' },
        { name: 'Hacks - Statistics', description: 'Aggregate statistics and charts' },
        { name: 'Hacks - Admin', description: 'ETL sync and admin operations' },
        { name: 'Skills - List & Filter', description: 'Browse and search AI skill files' },
        { name: 'Skills - Statistics', description: 'Skill aggregate statistics' },
        { name: 'Skills - Safety', description: 'Safety scan results and labels' },
        { name: 'Skills - Engagement', description: 'Copy and star engagement' },
        { name: 'Skills - Admin', description: 'Safety scan and sync admin operations' },
        { name: 'Forensics - POCs', description: 'Foundry exploit proof-of-concepts' },
        { name: 'Forensics - Simulation', description: 'Foundry simulation execution' },
        { name: 'Forensics - Trace', description: 'EVM transaction tracing' },
      ],
    },
  });

  await server.register(swaggerUi, {
    routePrefix: '/documentation',
    uiConfig: {
      docExpansion: 'list',
      deepLinking: true,
    },
  });

  // Register all route modules so paths appear in the spec
  await server.register(systemRoutes);
  await server.register(hacksRoutes);
  await server.register(forensicsRoutes);
  await server.register(skillsRoutes);

  await server.ready();
  return server;
}

// ═══════════════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════════════

describe('Swagger/OpenAPI Spec Validation — P1-ARCH-011', () => {
  let server: FastifyInstance;
  let spec: OpenAPISpec;

  beforeAll(async () => {
    server = await buildSwaggerServer();
    const res = await server.inject({ method: 'GET', url: '/documentation/json' });
    spec = JSON.parse(res.payload) as OpenAPISpec;
  });

  afterAll(async () => {
    await server.close();
  });

  // ── Spec Metadata ──────────────────────────────────────────────────────

  it('[SPEC-001] OpenAPI version is 3.1.0', () => {
    expect(spec.openapi).toBe('3.1.0');
  });

  it('[SPEC-002] spec.info.title is "AltFlex AEGIS API Gateway"', () => {
    expect(spec.info.title).toBe('AltFlex AEGIS API Gateway');
  });

  it('[SPEC-003] spec.info.version is "3.0.0"', () => {
    expect(spec.info.version).toBe('3.0.0');
  });

  it('[SPEC-004] spec.info.description mentions Backend-for-Frontend', () => {
    expect(spec.info.description).toContain('Backend-for-Frontend');
  });

  it('[SPEC-008] spec.info.license.name is "MIT"', () => {
    expect(spec.info.license?.name).toBe('MIT');
  });

  it('[SPEC-009] spec.info.contact.url contains github.com/Artificial-Ledger-Technology', () => {
    expect(spec.info.contact?.url).toContain('github.com/Artificial-Ledger-Technology');
  });

  // ── Tags ───────────────────────────────────────────────────────────────

  it('[SPEC-005] spec contains all 15 tags defined in swagger.plugin.ts', () => {
    const expectedTags = [
      'System - Health',
      'System - Meta',
      'System - Auth',
      'System - Rate Limit',
      'Hacks - List & Filter',
      'Hacks - Statistics',
      'Hacks - Admin',
      'Skills - List & Filter',
      'Skills - Statistics',
      'Skills - Safety',
      'Skills - Engagement',
      'Skills - Admin',
      'Forensics - POCs',
      'Forensics - Simulation',
      'Forensics - Trace',
    ];
    const tagNames = spec.tags.map((t) => t.name);
    for (const expected of expectedTags) {
      expect(tagNames).toContain(expected);
    }
  });

  // ── Paths ──────────────────────────────────────────────────────────────

  it('[SPEC-006] spec.paths is non-empty (routes are registered)', () => {
    const pathCount = Object.keys(spec.paths).length;
    expect(pathCount).toBeGreaterThan(0);
  });

  // ── Swagger UI ─────────────────────────────────────────────────────────

  it('[SPEC-007] GET /documentation/ returns successfully', async () => {
    const res = await server.inject({ method: 'GET', url: '/documentation/' });
    // Swagger UI should serve HTML or redirect — both valid
    expect([200, 302]).toContain(res.statusCode);
    if (res.statusCode === 200) {
      expect(res.headers['content-type']).toContain('text/html');
    }
  });
});
