'use client';

import React, { useState } from 'react';
import { Share2, FileText, Printer } from 'lucide-react';

interface ReportActionsProps {
  reportId: string;
}

export function ReportActions({ reportId }: ReportActionsProps): React.ReactNode {
  const [isCopied, setIsCopied] = useState(false);

  const handlePrint = (): void => {
    window.print();
  };

  const handleExportMarkdown = (): void => {
    // Generate a quick markdown payload for MVP
    const content = `# Forensic Report: ${reportId}\n\nGenerated by ALTFlex AEGIS.`;
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `forensic-report-${reportId}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShare = (): void => {
    const url = window.location.href;
    void navigator.clipboard.writeText(url).then(() => {
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    });
  };

  return (
    <div className="flex items-center gap-2 print:hidden">
      <button
        onClick={handleShare}
        className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-md hover:bg-slate-50 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-700 transition-colors"
      >
        <Share2 className="w-4 h-4" />
        {isCopied ? 'Copied!' : 'Share Link'}
      </button>

      <button
        onClick={handleExportMarkdown}
        className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-slate-700 bg-white border border-slate-300 rounded-md hover:bg-slate-50 dark:bg-slate-800 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-700 transition-colors"
      >
        <FileText className="w-4 h-4" />
        Markdown
      </button>

      <button
        onClick={handlePrint}
        className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-cyan-600 rounded-md hover:bg-cyan-700 transition-colors"
      >
        <Printer className="w-4 h-4" />
        Export PDF
      </button>
    </div>
  );
}
